name: CI

on: [push, pull_request]

env:
  GRADLE_OPTS: -Dhttp.keepAlive=false

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        jdk: [11, 17]

    steps:

    - name: Set up JDK for build and test
      uses: actions/setup-java@v2
      with:
        distribution: temurin # Temurin is a distribution of adoptium
        java-version: ${{ matrix.jdk }}

    - name: Checkout security
      uses: actions/checkout@v2

    - name: Test
      run: OPENDISTRO_SECURITY_TEST_OPENSSL_OPT=true ./gradlew test -i --tests org.opensearch.security.auditlog.compliance.ComplianceAuditlogTest.testComplianceEnable  

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: ${{ matrix.jdk }}-reports
        path: |
          ./build/reports/

    - name: check archive for debugging
      if: always()
      run: echo "Check the artifact ${{ matrix.jdk }}-reports.zip for detailed test results"
